### ISSUE TITLE
dev branch

### ISSUE THREAD

**Issue by Leon99** [zacharyrs/ha-melview#20]
It's been a while since the last commit to dev branch. Is there anything that prevents merging it to master?

**Comment by zacharyrs** [comment]
Hi @Leon99,

Sorry, I've completely left this project on hold - finally graduated and then it was straight into working full time.

I'm personally not happy with how the multi-zone support is implemented, hence why I've left it in the `dev` branch.
I also wanted to try to tackle the `async` stuff that home-assistant added before merging, which added to the backlog...

I'm not too sure when I'll fix this up, as I don't actually have the zones to test either.

Looks like this fork - https://github.com/haggis663/ha-melview - has implemented both zones and async, plus started releasing to HACS, so that's probably the best replacement.
